#!/bin/bash

# -----------------------###----------------------- #
#                      THESIS                       #
#                   ------------                    #
#           A personal forward operating base       #
#               and a Head in the Clouds            #
# -----------------------###----------------------- #
#                    LICENCE FIELD                  #
# -----------------------###----------------------- #
#                  TABLE OF CONTENTS                #
#              -----------------------              #
#   I.      Determening system's package manager    #
#   II.     Install packages                        #
#   III.    Stow symlinks                           #
#   IV.     Setup zsh                               #
# -----------------------###----------------------- #

# ------------------------------------- #
# I. DETERMINE SYSTEM'S PACKAGE MANAGER #
# ------------------------------------- #

# Declare a system -> package manager associative array.
declare -A PM_LOOKUP=(
    [/etc/debian_version]="apt"
)

# Determine package manager.
PACKAGE_MANAGER="NONE"

for file in ${!PM_LOOKUP[@]};
do
    echo "[*] Thesis is determining system's package manager"
    if [[ -f $file ]]; then
        PACKAGE_MANAGER=${PM_LOOKUP[$file]}
        echo "[+] Thesis has found $PACKAGE_MANAGER"
        break
    fi
done

# Abort if no suitable package manager was found.
if [ $PACKAGE_MANAGER = "NONE" ]; then
    echo "[-] Thesis cannot determine the systems package manager"
    echo "[*] Thesis is aborting installation ..."
    exit 1
fi

# -------------------- #
# II. INSTALL PACKAGES #
# -------------------- #

PACKAGES=(
    git         # Version control system.
    zsh         # Shell alternative.
    tmux        # Terminal multiplexer.
    stow        # Symlink farm.
    bat         # A better cat command.
    fzf         # Fuzzy finder.
    unzip	    # Extraction tool.
    nodejs      # Javascript runtime.
    npm         # Node package manager.
    cargo       # Rust package manager.
)

echo "[*] Thesis is installing ${#PACKAGES[@]} packages ..."

# Associatice array for package manager installation commands.
declare -A PMIC=(
    [apt]="sudo apt-get -y install"
)

# Install packages.
for package in ${PACKAGES[@]};
do
    echo "[*] Thesis is installing $package"
    eval "${PMIC[$PACKAGE_MANAGER]} $package" > /dev/null
done

# install pip packages.
PIP_PACKAGES=(
    black       # Python code formatter.
    flake8      # Python code linter.
    beautysh    # Bash code formatter.
)

echo "[*] Thesis is installing ${#PIP_PACKAGES[@]} pip packages ..."
for package in ${PIP_PACKAGES[@]};
do
    echo "[*] Thesis is installing $package"
    pip3 install $package > /dev/null
done

# Npm.
echo "[*] Thesis is installing npm packages"
echo "[*] Thesis is installing prettier"
npm install -g prettier

# Cargo.
echo "[*] Thesis is installing cargo packages"
echo "[*] Thesis is installing stylua"
cargo install stylua

echo "[*] Thesis is installing neovim"

# Set the appimage source and destination.
NEOVIM_SOURCE="https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
IMAGE_DESTINATION=$HOME/.local/bin
IMAGE_NAME=nvim
IMAGE=$IMAGE_DESTINATION/$IMAGE_NAME

# Download image and make it executeable.
curl -L $NEOVIM_SOURCE > $IMAGE
chmod u+x $IMAGE

# Display neovim version.
nvim --version | grep NVIM

echo "[*] Thesis installed neovim"
echo "[+] Thesis finished installing packages"

# ------------------ #
# III. STOW SYMLINKS #
# ------------------ #

# ------------- #
# IV. SETUP ZSH #
# ------------- #

echo "[*] Thesis is setting up ZSH"

if [ "$SHELL" != "/usr/bin/zsh" ] ; then
    
    # Get path of the zsh executable.
    zsh_path=$(which zsh)

    # Change shell for $USER to zsh.
    sudo chsh -s $zsh_path $USER
    
    # Explictly set the current shell as zsh.
    export SHELL=$zsh_path
fi

echo "[*] Thesis finished configuring ZSH"
