#!/bin/bash

# Determine package manager.
export PACKAGE_MANAGER="NONE"

# Packages to be installed via the package manager.
export declare -a PKG_MGR_PACKAGES=(
    git         # Version control system.
    zsh         # Shell alternative.
    tmux        # Terminal multiplexer.
    stow        # Symlink farm.
    bat         # A better cat command.
    fzf         # Fuzzy finder.
    unzip	    # Extraction tool.
    npm         # Node package manager.
    cargo       # Rust package manager.
    shellcheck  # Bash linter.
)

# Packages to be installed via pip.
export declare -a PIP_PACKAGES=(
    black       # Python code formatter.
    flake8      # Python code linter.
    beautysh    # Bash code formatter.
)

# Packages to be installed via npm.
export declare -a NPM_PACKAGES=(
    prettier    # Formatter -> https://www.npmjs.com/package/prettier.
    typescript  # Typescript compiler.
)

# Packages to be installed via cargo.
export declare -a CARGO_PACKAGES=(
    stylua      # Lua code formatter.
)

# Declare a system -> package manager associative array.
export declare -A PM_LOOKUP=(
    [/etc/debian_version]="apt"
)

# Declare a package manager -> install command associative array.
export declare -A PMIC=(
    [apt]="sudo apt-get -y install"
)
