#!/bin/bash

# -----------------------------------###----------------------------------- #
#                                  THESIS                                   #
#                               ------------                                #
#                       A personal forward operating base                   #
#                           and a Head in the Clouds                        #
# -----------------------------------###----------------------------------- #
#                                MIT License                                #
#                                                                           #
# Copyright (c) 2022 Alexander Robertson                                    #
#                                                                           #
# Permission is hereby granted, free of charge, to any person obtaining     #
# a copy of this software                                                   #
# and associated documentation files (the "Software"),                      #
# to deal in the Software without restriction, including without limitation #
# the rights to use, copy, modify, merge, publish, distribute, sublicense,  #
# and/or sell copies of the Software, and to permit persons to whom         #
# the Software is furnished to do so, subject to the following conditions:  #
#                                                                           #
# The above copyright notice and this permission notice shall be included   #
# in all copies or substantial portions of the Software.                    #
#                                                                           #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,           #
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO                          #
# THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE       #
# AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS   #
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,                      #
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,        #
# OUT OF OR IN CONNECTION WITH THE SOFTWARE                                 #
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                             #
# -----------------------------------###----------------------------------- #

source "./globals"
source "./functions"


# ------------------------------------- #
# I. DETERMINE SYSTEM'S PACKAGE MANAGER #
# ------------------------------------- #

# Use sudo here to require su-privileges for the program.
sudo clear
echo "--- THESIS ---"

notify operation "Thesis is determining system's package manager"
for file in "${!PM_LOOKUP[@]}";
do
    if [[ -f $file ]]; then
        PACKAGE_MANAGER=${PM_LOOKUP[$file]}
        notify success "Found $PACKAGE_MANAGER" true
        break
    fi
done

# Abort if no suitable package manager was found.
if [ "$PACKAGE_MANAGER" = "NONE" ]; then
    notify failure "Cannot determine system's package manager" true
    notify failure "Aborting installation ..."
    echo "--- THESIS ---"
    exit 1
fi


# -------------------- #
# II. INSTALL PACKAGES #
# -------------------- #

# Install package manager packages.
install_packages "$PACKAGE_MANAGER" "${PKG_MGR_PACKAGES[@]}"

# Install neovim from appimage.
notify operation "Thesis is installing Neovim from appimage"
SOURCE_DOMAIN="https://github.com"
SOURCE_DIR="/neovim/neovim/releases/latest/download/nvim.appimage"
NEOVIM_SOURCE="$SOURCE_DOMAIN$SOURCE_DIR"
NEOVIM_IMAGE=$HOME/.local/bin/nvim
curl -s -L $NEOVIM_SOURCE > "$NEOVIM_IMAGE"
chmod u+x "$NEOVIM_IMAGE" > /dev/null
command -v nvim &> /dev/null
if [ "$?" ]
then
    notify success "Thesis installed Neovim" true
else
    notify failure "Thesis failed to install Neovim" true
fi

# Install nodejs from source.
notify operation "Thesis is installing Nodejs from source"
curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash - &> /dev/null
sudo apt install nodejs &> /dev/null
command -v &> /dev/null
if [ "$?" ]
then
    notify success "Thesis installed Nodejs" true
else
    notify failure "Thesis failed to install Nodejs" true
fi

# Install pip packages.
install_packages pip "${PIP_PACKAGES[@]}"

# Install npm packages.
install_packages npm "${NPM_PACKAGES[@]}"

# Install cargo packages.
install_packages cargo "${CARGO_PACKAGES[@]}"


# ------------------ #
# III. STOW SYMLINKS #
# ------------------ #



# -------------------- #
# IV. SET ZSH AS SHELL #
# -------------------- #

if [ "$SHELL" != "/usr/bin/zsh" ] ; then
    
    # Get path of the zsh executable.
    zsh_path=$(command -v zsh)

    # Change shell for $USER to zsh.
    sudo chsh -s "$zsh_path" "$USER"
    
    # Explictly set the current shell as zsh.
    export SHELL=$zsh_path

    notify success "ZSH set as shell"
    notify debug "Please source .zshenv to setup zsh"
fi

echo "--- THESIS ---"
